#!/usr/bin/env python3
"""Generate a realistic phlo-transform workspace for dogfooding.

Writes ~120 models across several transform roots and namespaces, external
sources backed by seeds, tables and incrementals (append + keyed merge),
schema contracts, unique/not-null/custom tests, multi-hop dependencies and a
`failure_lab` namespace whose models fail only when `external.fail_flag`
contains a `boom` row — so failure/resume/retry-failed flows are exercised
without changing discovery.

Usage:
    scripts/dogfood_workspace.py [OUT_DIR] [--models N]

Defaults: OUT_DIR defaults to `fixtures/dogfood`, N to 120.
"""

from __future__ import annotations

import argparse
import csv
import random
import shutil
import sys
from pathlib import Path

ROOTS = {
    "ingest": "workflows/ingest/transforms",
    "assay": "workflows/assay/transforms",
    "reporting": "workflows/reporting/transforms",
    "finance": "domains/finance/transforms",
    "failure_lab": "workflows/failure_lab/transforms",
}

PHLO_TOML = """\
# Dogfooding workspace generated by scripts/dogfood_workspace.py.
[transform]
default_schema = "analytics"
default_materialization = "view"
default_namespace = "main"

[transform.discovery]
include = [
    "workflows/*/transforms/**",
    "domains/*/transforms/**",
]

[seeds]
schema = "external"

# Contracts on the two marts every workflow converges on: the schema the
# pipeline promises downstream readers.
[model."assay.marts.daily_analyte_summary".contract]
enforced = true

[model."assay.marts.daily_analyte_summary".columns.day]
type = "DATE"
nullable = false

[model."assay.marts.daily_analyte_summary".columns.analyte]
type = "VARCHAR"
nullable = false

[model."assay.marts.daily_analyte_summary".columns.mean_concentration]
type = "DOUBLE"
nullable = true

[model."finance.marts.daily_revenue".contract]
enforced = true

[model."finance.marts.daily_revenue".columns.day]
type = "DATE"
nullable = false

[model."finance.marts.daily_revenue".columns.revenue]
type = "DOUBLE"
nullable = false
"""

SEEDS = {
    "raw_samples": (
        ["sample_id", "matrix", "collected_at", "mass_g", "site_id"],
        lambda r: [
            f"SMP-{r:05d}",
            random.choice(["water", "soil", "tissue", "air"]),
            f"2024-{random.randint(1, 12):02d}-{random.randint(1, 28):02d}",
            round(random.uniform(0.1, 500.0), 2),
            f"SITE-{random.randint(1, 8):02d}",
        ],
        400,
    ),
    "raw_assays": (
        ["assay_id", "sample_id", "analyte", "concentration", "measured_at", "batch"],
        lambda r: [
            f"ASY-{r:05d}",
            f"SMP-{random.randint(0, 399):05d}",
            random.choice(["lead", "mercury", "arsenic", "cadmium", "pfos"]),
            round(random.uniform(0.001, 250.0), 4),
            # Space-separated timestamps cast cleanly on both DuckDB and
            # Trino — Trino rejects the ISO `T` separator.
            f"2024-{random.randint(1, 12):02d}-{random.randint(1, 28):02d} {random.randint(0, 23):02d}:00:00",
            f"B{random.randint(1, 40):03d}",
        ],
        2000,
    ),
    "raw_instruments": (
        ["instrument_id", "model", "lab", "calibrated_at"],
        lambda r: [
            f"INS-{r:03d}",
            random.choice(["ICP-MS-2000", "GC-Orbitrap", "LC-QQQ"]),
            random.choice(["north", "south", "central"]),
            f"2024-{random.randint(1, 12):02d}-{random.randint(1, 28):02d}",
        ],
        24,
    ),
    "raw_orders": (
        ["order_id", "customer_id", "amount", "ordered_at", "status"],
        lambda r: [
            f"ORD-{r:05d}",
            f"CUS-{random.randint(0, 149):04d}",
            round(random.uniform(5.0, 2000.0), 2),
            f"2024-{random.randint(1, 12):02d}-{random.randint(1, 28):02d}",
            random.choice(["paid", "paid", "paid", "refunded", "pending"]),
        ],
        800,
    ),
    "raw_customers": (
        ["customer_id", "name", "region", "segment"],
        lambda r: [
            f"CUS-{r:04d}",
            f"Customer {r}",
            random.choice(["emea", "amer", "apac"]),
            random.choice(["enterprise", "smb", "consumer"]),
        ],
        150,
    ),
    "raw_sites": (
        ["site_id", "name", "catchment", "active"],
        lambda r: [
            f"SITE-{r:02d}",
            f"Site {r}",
            random.choice(["north", "south", "east", "west"]),
            "true" if r % 9 else "false",
        ],
        12,
    ),
    # The failure switch: `boom` makes failure_lab models raise; anything
    # else keeps them a no-op empty select.
    "fail_flag": (["flag"], lambda r: ["ok"], 1),
}


def seed_files(out: Path) -> None:
    seeds = out / "seeds"
    seeds.mkdir(parents=True, exist_ok=True)
    for name, (header, row, count) in SEEDS.items():
        with (seeds / f"{name}.csv").open("w", newline="") as handle:
            writer = csv.writer(handle)
            writer.writerow(header)
            for i in range(count):
                writer.writerow(row(i))


def model(namespace: str, sub: str, name: str, sql: str, directives: list[str] | None = None) -> dict:
    return {"ns": namespace, "sub": sub, "name": name, "sql": sql, "directives": directives or []}


def ingest_models() -> list[dict]:
    specs = [
        ("stg_samples", "raw_samples", ["sample_id", "matrix", "collected_at", "mass_g", "site_id"]),
        ("stg_assays", "raw_assays", ["assay_id", "sample_id", "analyte", "concentration", "measured_at", "batch"]),
        ("stg_instruments", "raw_instruments", ["instrument_id", "model", "lab", "calibrated_at"]),
        ("stg_orders", "raw_orders", ["order_id", "customer_id", "amount", "ordered_at", "status"]),
        ("stg_customers", "raw_customers", ["customer_id", "name", "region", "segment"]),
        ("stg_sites", "raw_sites", ["site_id", "name", "catchment", "active"]),
    ]
    models = []
    for name, source, columns in specs:
        select_list = ",\n    ".join(columns)
        models.append(
            model(
                "ingest",
                "",
                name,
                f"select\n    {select_list}\nfrom external.{source}",
                directives=["@not-null " + columns[0], "@tags staging"],
            )
        )
    # One second-hop model so ingest is not a leaf-only namespace.
    models.append(
        model(
            "ingest",
            "",
            "active_sites",
            "select * from ingest.stg_sites where active = true",
        )
    )
    return models


def assay_models(extra: int) -> list[dict]:
    models = [
        model(
            "assay",
            "staging",
            "measurements",
            "select\n    a.assay_id,\n    a.sample_id,\n    a.analyte,\n    a.concentration,\n"
            "    cast(a.measured_at as timestamp) as measured_at,\n    a.batch,\n    s.matrix,\n    s.site_id\n"
            "from ingest.stg_assays a\njoin ingest.stg_samples s on s.sample_id = a.sample_id",
            directives=["@key assay_id", "@not-null sample_id,analyte"],
        ),
        model(
            "assay",
            "staging",
            "instrument_log",
            "select * from ingest.stg_instruments",
        ),
        model(
            "assay",
            "staging",
            "flagged_measurements",
            "select * from assay.staging.measurements where concentration > 100.0",
            directives=["@tags qc"],
        ),
    ]
    # Multi-hop intermediate layer: screen -> normalise -> enrich, chained
    # per analyte so dependency depth is real.
    analytes = ["lead", "mercury", "arsenic", "cadmium", "pfos"]
    for analyte in analytes:
        models.append(
            model(
                "assay",
                "intermediate",
                f"{analyte}_screened",
                f"select * from assay.staging.measurements where analyte = '{analyte}'",
            )
        )
        models.append(
            model(
                "assay",
                "intermediate",
                f"{analyte}_normalised",
                f"select *, concentration / nullif(max(concentration) over (), 0) as rel_concentration\n"
                f"from assay.intermediate.{analyte}_screened",
            )
        )
        models.append(
            model(
                "assay",
                "intermediate",
                f"{analyte}_by_site",
                "select site_id, analyte, count(*) as n, avg(concentration) as mean_concentration\n"
                f"from assay.intermediate.{analyte}_normalised\ngroup by site_id, analyte",
            )
        )
    # Second-wave intermediate models read the first wave — deeper graph.
    for i in range(extra):
        analyte = analytes[i % len(analytes)]
        models.append(
            model(
                "assay",
                "intermediate",
                f"lab_compare_{i:02d}",
                f"select a.site_id, a.analyte, a.mean_concentration, b.n as cohort_n\n"
                f"from assay.intermediate.{analyte}_by_site a\n"
                f"join assay.intermediate.{analyte}_by_site b on b.site_id = a.site_id and b.analyte = a.analyte",
                directives=["@tags comparison"],
            )
        )
    models += [
        model(
            "assay",
            "marts",
            "daily_analyte_summary",
            "select\n    coalesce(cast(measured_at as date), date '1970-01-01') as day,\n"
            "    coalesce(analyte, 'unknown') as analyte,\n    count(*) as measurements,\n"
            "    avg(concentration) as mean_concentration,\n    max(concentration) as max_concentration\n"
            "from assay.staging.measurements\n"
            "where measured_at is not null and analyte is not null\ngroup by 1, 2",
            directives=["@table", "@key day,analyte", "@not-null day,analyte", "@tags mart"],
        ),
        model(
            "assay",
            "marts",
            "sample_results",
            "select\n    s.sample_id,\n    s.matrix,\n    s.site_id,\n    m.assay_id,\n    m.analyte,\n    m.concentration\n"
            "from ingest.stg_samples s\njoin assay.staging.measurements m on m.sample_id = s.sample_id",
            directives=["@incremental key=assay_id", "@tags mart"],
        ),
        model(
            "assay",
            "marts",
            "measurement_log",
            "select assay_id, sample_id, analyte, concentration, measured_at, batch\n"
            "from assay.staging.measurements",
            directives=["@incremental append", "@tags mart"],
        ),
        model(
            "assay",
            "marts",
            "batch_summary",
            "select batch, analyte, count(*) as n, avg(concentration) as mean_concentration\n"
            "from assay.staging.measurements\ngroup by 1, 2",
            directives=["@incremental key=batch,analyte"],
        ),
        model(
            "assay",
            "marts",
            "daily_exceedances",
            "select cast(measured_at as date) as day, count(*) as exceedances\n"
            "from assay.staging.flagged_measurements\ngroup by 1",
            directives=["@incremental window=day", "@tags mart"],
        ),
    ]
    for analyte in analytes:
        models.append(
            model(
                "assay",
                "qc",
                f"{analyte}_qc_report",
                f"select *, case when mean_concentration > 50 then 'review' else 'ok' end as qc_status\n"
                f"from assay.intermediate.{analyte}_by_site",
                directives=["@tags qc"],
            )
        )
    return models


def reporting_models() -> list[dict]:
    models = []
    analytes = ["lead", "mercury", "arsenic", "cadmium", "pfos"]
    for i, analyte in enumerate(analytes):
        models.append(
            model(
                "reporting",
                "",
                f"{analyte}_dashboard",
                f"select d.day, d.analyte, d.mean_concentration, d.measurements\n"
                f"from assay.marts.daily_analyte_summary d\nwhere d.analyte = '{analyte}'",
                directives=["@tags dashboard"],
            )
        )
    models += [
        model(
            "reporting",
            "",
            "site_scorecard",
            "select\n    site_id,\n    analyte,\n    sum(n) as measurements,\n    avg(mean_concentration) as mean_concentration\n"
            "from (\n"
            "    select * from assay.intermediate.lead_by_site\n"
            "    union all select * from assay.intermediate.mercury_by_site\n"
            "    union all select * from assay.intermediate.arsenic_by_site\n"
            "    union all select * from assay.intermediate.cadmium_by_site\n"
            "    union all select * from assay.intermediate.pfos_by_site\n"
            ")\ngroup by 1, 2",
            directives=["@tags scorecard"],
        ),
        model(
            "reporting",
            "",
            "weekly_brief",
            "select day, sum(measurements) as measurements, avg(mean_concentration) as mean_concentration\n"
            "from assay.marts.daily_analyte_summary\ngroup by 1",
        ),
        model(
            "reporting",
            "",
            "revenue_vs_exposure",
            "select\n    r.day,\n    r.revenue,\n    e.exceedances\n"
            "from finance.marts.daily_revenue r\n"
            "left join assay.marts.daily_exceedances e on e.day = r.day",
            directives=["@tags cross-domain"],
        ),
    ]
    # A tail of thin reporting views so the namespace is realistically wide.
    for i in range(12):
        analyte = analytes[i % len(analytes)]
        models.append(
            model(
                "reporting",
                "ops",
                f"ops_snapshot_{i:02d}",
                f"select site_id, analyte, mean_concentration\n"
                f"from assay.qc.{analyte}_qc_report\nwhere qc_status = '{'review' if i % 3 == 0 else 'ok'}'",
            )
        )
    return models


def finance_models() -> list[dict]:
    models = [
        model(
            "finance",
            "staging",
            "orders",
            "select\n    order_id,\n    customer_id,\n    cast(amount as double) as amount,\n"
            "    cast(ordered_at as date) as ordered_on,\n    status\n"
            "from ingest.stg_orders\nwhere amount is not null and ordered_at is not null",
            directives=["@key order_id"],
        ),
        model(
            "finance",
            "staging",
            "customers",
            "select * from ingest.stg_customers",
            directives=["@key customer_id"],
        ),
        model(
            "finance",
            "intermediate",
            "paid_orders",
            "select * from finance.staging.orders where status = 'paid'",
        ),
        model(
            "finance",
            "intermediate",
            "customer_orders",
            "select\n    c.customer_id,\n    c.region,\n    c.segment,\n    o.order_id,\n    o.amount,\n    o.ordered_on\n"
            "from finance.staging.customers c\njoin finance.staging.orders o on o.customer_id = c.customer_id",
        ),
        model(
            "finance",
            "marts",
            "daily_revenue",
            "select coalesce(ordered_on, date '1970-01-01') as day, coalesce(sum(amount), 0.0) as revenue,\n"
            "    count(*) as orders\nfrom finance.intermediate.paid_orders\ngroup by 1",
            directives=["@table", "@key day", "@not-null day", "@tags mart"],
        ),
        model(
            "finance",
            "marts",
            "customer_lifetime_value",
            "select customer_id, region, segment, sum(amount) as lifetime_value, count(*) as orders\n"
            "from finance.intermediate.customer_orders\ngroup by 1, 2, 3",
            directives=["@incremental key=customer_id", "@tags mart"],
        ),
        model(
            "finance",
            "marts",
            "order_events",
            "select order_id, customer_id, amount, ordered_on, status\nfrom finance.staging.orders",
            directives=["@incremental append"],
        ),
        model(
            "finance",
            "marts",
            "region_monthly",
            "select region, date_trunc('month', ordered_on) as month, sum(amount) as revenue\n"
            "from finance.intermediate.customer_orders\ngroup by 1, 2",
            directives=["@incremental key=region,month"],
        ),
    ]
    for region in ["emea", "amer", "apac"]:
        models.append(
            model(
                "finance",
                "intermediate",
                f"{region}_customers",
                f"select * from finance.staging.customers where region = '{region}'",
            )
        )
        models.append(
            model(
                "finance",
                "intermediate",
                f"{region}_revenue",
                f"select c.region, o.ordered_on, sum(o.amount) as revenue\n"
                f"from finance.intermediate.{region}_customers c\n"
                f"join finance.staging.orders o on o.customer_id = c.customer_id\ngroup by 1, 2",
            )
        )
    return models


def failure_lab_models() -> list[dict]:
    # The cast is only evaluated for rows that survive the filter, so the
    # model is a clean empty build until the fail_flag seed carries `boom`.
    # `cast` is portable across DuckDB and Trino, unlike `error()`/`fail()`.
    return [
        model(
            "failure_lab",
            "",
            "guarded_gate",
            "select cast(flag as int) as failure\n"
            "from external.fail_flag\nwhere flag = 'boom'",
        ),
        model(
            "failure_lab",
            "",
            "downstream_of_gate",
            "select * from failure_lab.guarded_gate",
        ),
        model(
            "failure_lab",
            "",
            "independent_control",
            "select 1 as control",
        ),
    ]


TESTS = {
    "stg_samples_no_duplicate_ids.sql": (
        "select sample_id from ingest.stg_samples group by 1 having count(*) > 1"
    ),
    "stg_assays_sample_fk.sql": (
        "select a.sample_id from ingest.stg_assays a\n"
        "left join ingest.stg_samples s on s.sample_id = a.sample_id\n"
        "where s.sample_id is null"
    ),
    "measurements_nonnegative.sql": (
        "select assay_id from assay.staging.measurements where concentration < 0"
    ),
    "daily_summary_complete_analytes.sql": (
        "select analyte from assay.marts.daily_analyte_summary\n"
        "where analyte not in ('lead', 'mercury', 'arsenic', 'cadmium', 'pfos')"
    ),
    "daily_revenue_positive.sql": (
        "select day from finance.marts.daily_revenue where revenue <= 0"
    ),
    "customer_ltv_no_orphans.sql": (
        "select c.customer_id from finance.marts.customer_lifetime_value c\n"
        "left join finance.staging.customers s on s.customer_id = c.customer_id\n"
        "where s.customer_id is null"
    ),
    "site_scorecard_known_sites.sql": (
        "select r.site_id from reporting.site_scorecard r\n"
        "left join ingest.stg_sites s on s.site_id = r.site_id\n"
        "where s.site_id is null"
    ),
    "instruments_calibrated.sql": (
        "select instrument_id from ingest.stg_instruments where calibrated_at is null"
    ),
}


def write_models(out: Path, models: list[dict]) -> int:
    count = 0
    for spec in models:
        folder = out / ROOTS[spec["ns"]] / spec["sub"]
        folder.mkdir(parents=True, exist_ok=True)
        text = "".join(f"-- {directive}\n" for directive in spec["directives"])
        (folder / f"{spec['name']}.sql").write_text(f"{text}{spec['sql']}\n")
        count += 1
    return count


def write_folder_configs(out: Path) -> None:
    # Folder-level defaults live in the transforms root's transform.toml as
    # `[folder.<name>]` sections — marts materialise as tables, staging and
    # qc stay views.
    configs = {
        "workflows/assay/transforms": (
            'materialized = "view"\n\n'
            '[folder.marts]\nmaterialized = "table"\ntags = ["mart"]\n\n'
            '[folder.staging]\nmaterialized = "view"\ntags = ["staging"]\n\n'
            '[folder.qc]\nmaterialized = "view"\ntags = ["qc"]\n'
        ),
        "workflows/failure_lab/transforms": 'materialized = "table"\ntags = ["lab"]\n',
        "workflows/ingest/transforms": 'materialized = "view"\ntags = ["ingest"]\n',
        "domains/finance/transforms": (
            'materialized = "view"\n\n'
            '[folder.marts]\nmaterialized = "table"\ntags = ["mart"]\n\n'
            '[folder.staging]\nmaterialized = "view"\ntags = ["staging"]\n'
        ),
    }
    for rel, body in configs.items():
        path = out / rel
        path.mkdir(parents=True, exist_ok=True)
        (path / "transform.toml").write_text(body)


def write_tests(out: Path) -> None:
    tests = out / "tests"
    tests.mkdir(parents=True, exist_ok=True)
    for name, sql in TESTS.items():
        (tests / name).write_text(sql + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("out", nargs="?", default="fixtures/dogfood")
    parser.add_argument("--models", type=int, default=120)
    parser.add_argument("--seed", type=int, default=7)
    args = parser.parse_args()
    random.seed(args.seed)

    out = Path(args.out)
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    base = (
        ingest_models()
        + assay_models(extra=10)
        + reporting_models()
        + finance_models()
        + failure_lab_models()
    )
    # Scale to the requested size with additional assay intermediates.
    if len(base) < args.models:
        analytes = ["lead", "mercury", "arsenic", "cadmium", "pfos"]
        for i in range(args.models - len(base)):
            analyte = analytes[i % len(analytes)]
            base.append(
                model(
                    "assay",
                    "intermediate",
                    f"rolled_{i:03d}",
                    f"select site_id, analyte, n, mean_concentration\n"
                    f"from assay.intermediate.{analyte}_by_site\n"
                    f"where n > {i % 5}",
                )
            )

    written = write_models(out, base)
    seed_files(out)
    write_tests(out)
    write_folder_configs(out)
    (out / "phlo.toml").write_text(PHLO_TOML)
    (out / "README.md").write_text(
        "# dogfood workspace\n\nGenerated by `scripts/dogfood_workspace.py` — a\n"
        "deliberately realistic project for exercising phlo-transform end to\n"
        "end: several roots and namespaces, seed-backed external sources,\n"
        "tables and incrementals (append + keyed merge + time window),\n"
        "contracts, tests and a `failure_lab` namespace driven by the\n"
        "`fail_flag` seed (flip the row to `boom` to make those models fail,\n"
        "then exercise `--resume` / `--retry-failed`).\n"
    )
    print(f"wrote {written} models, {len(SEEDS)} seeds, {len(TESTS)} tests to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
